{
  users {
    id
    idEncoded
    fullName
    email
    comments {
      body
      author {
        id
      }
      post {
        body
        author {
          id
        }
      }
    }
    following {
      fullName
    }
  }
}
