const users = [ { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 91 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 216 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 295 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 516 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 593 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 652 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 782 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The ADP bus is down, compress the mobile pixel so we can compress the SCSI firewall!',
    posts__comments__author__id: 842,
    posts__comments__author__first_name: 'Kenyatta',
    posts__comments__author__last_name: 'Kessler',
    posts__comments__author__email_address: 'Brady_White61@yahoo.com',
    posts__comments__author__following__id: 996 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The HTTP bandwidth is down, generate the cross-platform bus so we can hack the SSL bus!',
    posts__comments__author__id: 346,
    posts__comments__author__first_name: 'Lorna',
    posts__comments__author__last_name: 'Sipes',
    posts__comments__author__email_address: 'Easton24@gmail.com',
    posts__comments__author__following__id: 44 },
  { id: 8,
    first_name: 'Ignacio',
    last_name: 'Kling',
    email_address: 'Laron79@hotmail.com',
    posts__id: 120,
    posts__body: 'Sed quis quasi quaerat libero hic quas soluta voluptatibus veniam. Molestiae porro cum amet non commodi veritatis. Quos error est corporis cupiditate. Harum vel aut assumenda voluptatibus odio sit ut error velit.',
    posts__comments__body: 'The HTTP bandwidth is down, generate the cross-platform bus so we can hack the SSL bus!',
    posts__comments__author__id: 346,
    posts__comments__author__first_name: 'Lorna',
    posts__comments__author__last_name: 'Sipes',
    posts__comments__author__email_address: 'Easton24@gmail.com',
    posts__comments__author__following__id: 268 } ]

  const nestDef = { first_name: 'first_name',
    last_name: 'last_name',
    id: 'id',
    email: 'email_address',
    posts:
     [ { id: 'posts__id',
            body: 'posts__body',
            comments:
             { body: 'posts__comments__body',
                       author:
                        { first_name: 'posts__comments__author__first_name',
                                     last_name: 'posts__comments__author__last_name',
                                     id: 'posts__comments__author__id',
                                     email: 'posts__comments__author__email_address',
                                     following: [ { id: 'posts__comments__author__following__id' } ] } } } ] }

  const { nest } = require('nesthydrationjs')
  const slice = users.slice(-3)
  console.log(slice)
  nest(slice, nestDef)
