site_name: Join Monster
site_description: A GraphQL-to-SQL execution layer.
repo_url: https://github.com/join-monster/join-monster
site_favicon: img/join_monster.ico
theme: readthedocs
extra_javascript:
  # MkDocs includes an old version of highlight.js, but it doesn't recognize all modern JS syntax, import a newer version
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js
  - custom.js
extra_css: 
  - custom.css
pages:
  - Introduction: index.md
  - "The Problem We Solve": problem.md
  - "How It Works": how-it-works.md
  - "Basic Usage":
    - "1. Declare Data Model": data-model.md
    - "2. Map Objects to Tables": map-to-table.md
    - "3. Add Metadata to Fields": field-metadata.md
    - "4. Calling Join Monster": call-function.md
    - "5. Where Conditions": where.md
    - "6. Joining Objects": start-joins.md
    - "7. Arbitrary Depth": arbitrary-depth.md
    - "8. Many-to-Many Joins": many-to-many.md
    - "9. Order By": order-by.md
  - "Query Planning":
    - "What & Why": query-planning.md
    - "One-to-many Batch": batch-one-many.md
    - "Many-to-many Batch": batch-many-many.md
  - "Advanced Usage":
    - "Misc. Properties": misc.md
    - "Union & Interface Types": unions.md
    - "Aggregation Tricks": aggregation.md
    - "Pagination": pagination.md
    - "Relay Support": relay.md
  - "SQL Dialects": dialects.md
  - Warnings: warnings.md
  - API: API.md
  - "Change Log": CHANGELOG.md
