{
  users {
    ...UserInfo
    posts {
      id
      body
      comments {
        body
        author {
          ... UserInfo
          following {
            id
          }
        }
      }
    }
  }
}

fragment UserInfo on User {
  id, fullName, email
}
