name: 'PR Tasks Completed Check'

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  task-check:
    name: Task Check
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
